ALTER TABLE users
    ADD COLUMN IF NOT EXISTS is_verified     BOOLEAN   NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS otp_code        VARCHAR(6),
    ADD COLUMN IF NOT EXISTS otp_expires_at  TIMESTAMP WITH TIME ZONE;
