package handler

import (
	"bytes"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"github.com/teymurovtural/ttshelf-backend/internal/domain"
	"github.com/teymurovtural/ttshelf-backend/internal/middleware"
	"github.com/teymurovtural/ttshelf-backend/internal/storage"
	"github.com/teymurovtural/ttshelf-backend/pkg/apperror"
	"github.com/teymurovtural/ttshelf-backend/pkg/response"
)

const maxExportSize = 50 << 20 // 50MB

type ExportHandler struct {
	canvasService domain.CanvasService
	minio         *storage.MinioClient
	publicURL     string
}

func NewExportHandler(canvasService domain.CanvasService, minio *storage.MinioClient, publicURL string) *ExportHandler {
	return &ExportHandler{
		canvasService: canvasService,
		minio:         minio,
		publicURL:     publicURL,
	}
}

// ExportPDF godoc
// @Summary      Export canvas as PDF
// @Tags         canvases
// @Accept       multipart/form-data
// @Produce      json
// @Security     BearerAuth
// @Param        id   path string true "Canvas ID"
// @Param        file formData file true "PDF file generated by frontend (max 50MB)"
// @Success      200 {object} domain.ExportPDFResponse
// @Failure      400 {object} response.Response
// @Failure      404 {object} response.Response
// @Router       /canvases/{id}/export/pdf [post]
func (h *ExportHandler) ExportPDF(w http.ResponseWriter, r *http.Request) {
	userID := middleware.GetUserID(r)
	canvasID := chi.URLParam(r, "id")

	// Canvas user-ə məxsusdurmu yoxla
	if _, err := h.canvasService.ExportPDF(r.Context(), canvasID, userID, nil); err != nil {
		if appErr, ok := err.(*apperror.AppError); ok {
			response.Error(w, appErr)
			return
		}
		response.Error(w, apperror.ErrInternalError)
		return
	}

	if err := r.ParseMultipartForm(maxExportSize); err != nil {
		response.Error(w, apperror.New("FILE_TOO_LARGE", "PDF maksimum 50MB ola bilər", http.StatusBadRequest))
		return
	}

	file, header, err := r.FormFile("file")
	if err != nil {
		response.Error(w, apperror.New("FILE_REQUIRED", "PDF fayl tələb olunur", http.StatusBadRequest))
		return
	}
	defer file.Close()

	// MIME yoxla
	buf := make([]byte, 512)
	n, _ := file.Read(buf)
	mimeType := http.DetectContentType(buf[:n])
	if mimeType != "application/pdf" {
		// jsPDF bəzən "application/octet-stream" göndərə bilər, header-a da bax
		ct := header.Header.Get("Content-Type")
		if ct != "application/pdf" {
			response.Error(w, apperror.New("INVALID_FILE_TYPE", "Yalnız PDF qəbul edilir", http.StatusBadRequest))
			return
		}
	}

	// Faylı başa qaytar
	if _, err := file.Seek(0, 0); err != nil {
		response.Error(w, apperror.ErrInternalError)
		return
	}

	// Köhnə PDF varsa üzərinə yaz — eyni key istifadə et
	objectKey := fmt.Sprintf("exports/%s/%s.pdf", userID, canvasID)

	// Faylı oxu
	var buf2 bytes.Buffer
	if _, err := buf2.ReadFrom(file); err != nil {
		response.Error(w, apperror.ErrInternalError)
		return
	}
	pdfBytes := buf2.Bytes()

	// Yeni UUID istifadə et ki, cache-lənmiş köhnə versiya gəlməsin
	objectKey = fmt.Sprintf("exports/%s/%s_%s.pdf", userID, canvasID, uuid.New().String()[:8])

	if err := h.minio.Upload(
		r.Context(),
		objectKey,
		"application/pdf",
		bytes.NewReader(pdfBytes),
		int64(len(pdfBytes)),
	); err != nil {
		response.Error(w, apperror.ErrInternalError)
		return
	}

	url := fmt.Sprintf("%s/%s/%s", h.publicURL, h.minio.BucketName(), objectKey)

	response.OK(w, domain.ExportPDFResponse{
		URL: url,
		Key: objectKey,
	})
}
